### ISSUE TITLE
Debugger Errors: Index p_bone = -1 is out of bounds (bone_size = 7)

### ISSUE THREAD

**Issue by manujarvinen** [yaelatletl/godot-jigglebones#10]
I did everything like in the instructions and I'm getting these errors per every frame :(
`Index p_bone = -1 is out of bounds (bone_size = 7)`

Other than the errors, everything functions just fine, I like how it jiggles :)

What to do?

![image](https://github.com/yaelatletl/godot-jigglebones/assets/5437697/6eb799a5-2958-4b2f-aeaf-f40349ddca01)

![car_antenna](https://github.com/yaelatletl/godot-jigglebones/assets/5437697/00aef19b-06bb-4c21-8def-ae6588c5e967)

**Comment by Genesis412** [comment]
> I did everything like in the instructions and I'm getting these errors per every frame :( `Index p_bone = -1 is out of bounds (bone_size = 7)`
> 
> Other than the errors, everything functions just fine, I like how it jiggles :)
> 
> What to do?
> 
> ![image](https://user-images.githubusercontent.com/5437697/266919048-6eb799a5-2958-4b2f-aeaf-f40349ddca01.png)
> 
> ![car_antenna](https://user-images.githubusercontent.com/5437697/266919718-00aef19b-06bb-4c21-8def-ae6588c5e967.gif) [ ![car_antenna](https://user-images.githubusercontent.com/5437697/266919718-00aef19b-06bb-4c21-8def-ae6588c5e967.gif) ](https://user-images.githubusercontent.com/5437697/266919718-00aef19b-06bb-4c21-8def-ae6588c5e967.gif) [ ](https://user-images.githubusercontent.com/5437697/266919718-00aef19b-06bb-4c21-8def-ae6588c5e967.gif)

Had the same issue. Fixed by parenting the bones that i wanted to jiggle to another part of the skeleton that was not influenced by jiggle.

**Comment by manujarvinen** [comment]
Thank you [Genesis412](https://github.com/Genesis412)! That solved it! 

Or in other words: just add a root bone, that you are not going to jiggle and parent the bones that you will jiggle onto the root bone.

I shall close this as resolved now :)
