### ISSUE TITLE
Completely broken?

### ISSUE THREAD

**Issue by Damnae** [yaelatletl/godot-jigglebones#6]
- It's set to run as a tool but doesn't work in the editor, it tilts the whole model because it starts without a bone name, and doesn't update bone ids when the bone name is changed. 
- ~~Gravity doesn't work, it seems to be applied in the bone's local space and points in the wrong direction.~~ Turns out gravity works, it's actually the only thing that works, but it expects blender bones default forward axis to be -Z, when it is actually +Y.
- ~~It's not just gravity actually, all motion seem to be applied relative to the bone's "forward axis", even when it makes no sense for the movement.~~ All motion that isn't gravity is applied as if the bone's forward axis is -Z, ignoring the Forward Axis option. Line 68 needs to be changed by replacing `Vector3(0, 0, -1)` by `get_bone_forward_local()`.
- In the editor bones jiggle in the wrong (opposite) direction, but it somehow works while running the game. Likely because top_level doesn't do anything in the editor.

**Comment by yaelatletl** [comment]
Thank you for the comment, I'll check it, as I remember this being functional, you tried it with 4.0.2?

**Comment by Damnae** [comment]
Yes

**Comment by yaelatletl** [comment]
Could you write your system's specs? This project is working fine on my end (No model tilt, works as tool, fix for line 68 does work tho). 
Also the editor jiggle direction is a wontfix. It's not worth it to try and workaround this

**Comment by Damnae** [comment]
The problem will show when you add a new jigglebone. Because everything is initialized in _ready, it won't initialize bone id variables. Once you type the actual bone name, they stay at 0 and will move one of the root bone. As it is you have to set the bone name and restart the whole editor to make it work.

**Comment by yaelatletl** [comment]
I've pushed two commits to main, please test if they solve the issues you mentioned
